### ISSUE TITLE
counsel-projectile-on

### ISSUE THREAD

**Issue by gburnett** [thefrontside/frontmacs#96] opened 2018-01-02 19:45 UTC
When I open emacs I encounter the following warning:
```
Warning (initialization): An error occurred while loading ‘/home/gburnett/.emacs.d/init.el’:

Symbol's function definition is void: counsel-projectile-on

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
I follow the debugging advice
```
Debugger entered--Lisp error: (void-function counsel-projectile-on)
  counsel-projectile-on()
  byte-code("\306\307!\210\306\310!\210\306\311!\210\306\312!\210\306\313!\210\314\315!\210\316\317 \210\320\321\322\323\324\325\315!\210\326\327!\207" [projectile-completion-system ivy-re-builders-alist company-idle-delay company-tooltip-limit company-minimum-prefix-length company-tooltip-flip-when-above require swiper company counsel-projectile flx smex ivy-mode 1 ivy counsel-projectile-on ((swiper . ivy--regex-plus) (t . ivy--regex-fuzzy)) 0.5 10 2 t global-company-mode provide frontmacs-completion] 2)
  require(frontmacs-completion)
  eval-buffer(#<buffer  *load*-331489> nil "/home/gburnett/.emacs.d/elpa/frontmacs-0.2.16/frontmacs.el" nil t)  ; Reading at buffer position 231
  load-with-code-conversion("/home/gburnett/.emacs.d/elpa/frontmacs-0.2.16/frontmacs.el" "/home/gburnett/.emacs.d/elpa/frontmacs-0.2.16/frontmacs.el" nil t)
  require(frontmacs)
  eval-buffer(#<buffer  *load*-238261> nil "/home/gburnett/.emacs.d/init-frontmacs.el" nil t)  ; Reading at buffer position 2576
  load-with-code-conversion("/home/gburnett/.emacs.d/init-frontmacs.el" "/home/gburnett/.emacs.d/init-frontmacs.el" nil nil)
  load("/home/gburnett/.emacs.d/init-frontmacs.el")
  eval-buffer(#<buffer  *load*> nil "/home/gburnett/.emacs.d/init.el" nil t)  ; Reading at buffer position 361
  load-with-code-conversion("/home/gburnett/.emacs.d/init.el" "/home/gburnett/.emacs.d/init.el" t t)
  load("/home/gburnett/.emacs.d/init" t t)
  #[0 "\205\266	\306=\203\307\310Q\202?	\311=\204\307\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210\324=\203e\326\327\330\307\331Q!\"\325\324\211#\210\324=\203d\210\203\247\332!\333\232\203\247\334!\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337\"\203\243\340\341#\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()
```
When I look at line 27 of frontmacs-completion.el I see that `counsel-projectile-on` is used.  According to the [counsel-projectile documentation](https://github.com/ericdanan/counsel-projectile#key-bindings) it no longer exists.

Should this use `counsel-projectile-mode` instead?

**Comment by sadatay** [comment] 2018-01-02 19:52
Heya @gburnett , thanks for reporting this.  I actually noticed this myself about a week ago and I have a PR out for it: https://github.com/thefrontside/frontmacs/pull/95 .  We haven't released it yet but it should be coming soon.

**Comment by sadatay** [comment] 2018-01-03 01:09
@gburnett, first of all thank you again for using frontmacs, and for helping us to make frontmacs better!  you rock 😄 .  we got https://github.com/thefrontside/frontmacs/pull/95 over the fence this afternoon and the issue is resolved in [v0.2.17](https://github.com/thefrontside/frontmacs/releases/tag/v0.2.17) .  you will probably need to blow away your `elpa` directory and reinstall frontmacs at this newest version to resolve the problem.  let us know if that works for you and if so we'll go ahead and close the issue.

**Comment by gburnett** [comment] 2018-01-03 14:40
@sadatay It is working for me now.  Thank you very much.

Note to self: check pull requests before raising issues.

**Comment by sadatay** [comment] 2018-01-03 15:31
no worries!  happy to hear it's working for you now.  i'll go ahead and close this

**Closed as completed by sadatay** 2018-01-03 15:31 UTC

**Comment by cowboyd** [comment] 2018-01-03 15:33
> you will probably need to blow away your elpa directory and reinstall frontmacs at this newest version to resolve the problem.

You should be able to just do a `M-x package-list` and select frontmacs for upgrading, and then restart emacs. No need to blow away your `elpa` dir.
